# Site settings
title: Daphne Soegijono
email: d.soegijono@gmail.com
description: "The personal website of Daphne Soegijono."
baseurl: ""
url: "http://dsoegijono.github.io"

# Build settings
markdown: kramdown
permalink: pretty
