# Site settings
title: Daphne Soegijono
email: me@daphnesoegijono.com
description: "The personal website of Daphne Soegijono."
baseurl: ""
url: "http://www.daphnesoegijono.com"
username: dsoegijono

# Build settings
markdown: kramdown
permalink: pretty
