- name: AngelList
  url: https://angel.co/dsoegijono
  icon: angellist

- name: Blogger
  url: http://dsoegijono.blogspot.com
  icon: pencil

- name: Facebook
  url: https://www.facebook.com/d.soegijono
  icon: facebook-square

- name: GitHub
  url: https://www.github.com/dsoegijono
  icon: github

- name: Instagram
  url: http://instagram.com/dsoegijono
  icon: instagram

- name: jsfiddle
  url: http://jsfiddle.net/user/dsoegijono/
  icon: jsfiddle

- name: Last.fm
  url: http://www.last.fm/user/dsoegijono
  icon: lastfm-square

- name: LinkedIn
  url: http://www.linkedin.com/in/dsoegijono
  icon: linkedin

- name: Mastodon
  url: https://mastodon.au/@thisisdee
  icon: mastodon

- name: Reddit
  url: http://www.reddit.com/user/thisisdee
  icon: reddit

- name: Skype
  url: skype:dsoegijono?userinfo
  icon: skype

- name: stackoverflow
  url: http://stackoverflow.com/users/861815/dee
  icon: stack-overflow

- name: Steam
  url: http://steamcommunity.com/id/dsoegijono
  icon: steam-square

- name: Twitter
  url: https://www.twitter.com/dsoegijono
  icon: twitter

- name: World Cube Association
  url: https://www.worldcubeassociation.org/persons/2018SOEG01
  icon: cube
