- name: AngelList
  url: https://angel.co/dsoegijono
  icon: angellist

- name: Ask.fm
  url: http://ask.fm/dsoegijono
  icon: question

- name: Blogger
  url: http://dsoegijono.blogspot.com
  icon: pencil

- name: Codecademy
  url: http://www.codecademy.com/dsoegijono
  icon: code

- name: Facebook
  url: https://www.facebook.com/d.soegijono
  icon: facebook-square

- name: GitHub
  url: https://www.github.com/dsoegijono
  icon: github

- name: Google+
  url: https://plus.google.com/105299270876688639508/
  icon: google-plus-square

- name: Instagram
  url: http://instagram.com/dsoegijono
  icon: instagram

- name: jsfiddle
  url: http://jsfiddle.net/user/dsoegijono/
  icon: jsfiddle

- name: Last.fm
  url: http://www.last.fm/user/dsoegijono
  icon: lastfm-square

- name: LinkedIn
  url: http://www.linkedin.com/in/dsoegijono
  icon: linkedin

- name: Reddit
  url: http://www.reddit.com/user/thisisdee
  icon: reddit

- name: Skype
  url: skype:dsoegijono?userinfo
  icon: skype

- name: Spotify
  url: https://play.spotify.com/user/dsoegijono
  icon: spotify

- name: stackoverflow
  url: http://stackoverflow.com/users/861815/dee
  icon: stack-overflow

- name: Steam
  url: http://steamcommunity.com/id/dsoegijono
  icon: steam-square

- name: Twitter
  url: https://www.twitter.com/dsoegijono
  icon: twitter
